networks:
  caddy:
    external: true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/external/configs/lidarr:/config
      - /media/external/library/music:/music
      - /media/external/library/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - caddy
