networks:
  caddy:
    external: true

services:
  homeassistant:
    restart: unless-stopped
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external2/homeassistant-config:/config
      - ./home-assistant/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /media/external/library:/library
    privileged: true
    network_mode: host

  downloader:
    restart: unless-stopped
    container_name: downloader
    user: "1000:1000"
    image: ghcr.io/deanshub/downloader:master
    depends_on:
      - telegram-bot-api
    env_file:
      - ./downloader/.env
    volumes:
      - /media/external:/media/external
      - /media/external2:/media/external2
    privileged: true

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    user: "1000:1000"
    env_file:
      - ./telegram-bot-api/.env
    volumes:
      - /media/external/configs/telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  friday:
    restart: unless-stopped
    container_name: friday
    user: "1000:1000"
    build: ./friday
    # image:
    env_file:
      - ./friday/.env
    volumes:
      - /media/external:/media/external
    privileged: true

  shopping-bot:
    restart: unless-stopped
    container_name: shopping-bot
    user: "1000:1000"
    image: ghcr.io/deanshub/shopping-bot:main
    env_file:
      - ./shopping-bot/.env
    volumes:
      - /media/external:/media/external
    privileged: true

  # auto-git:
  #   restart: unless-stopped
  #   user: root
  #   container_name: auto-git
  #   build: ./auto-git
  #   # image:
  #   env_file:
  #     - ./auto-git/.env
  #   ports:
  #     - 7005:7005
  #   volumes:
  #     - /media/external/auto-git/repos:/repos
  #     - /media/external/auto-git/apps:/apps
  #   networks:
  #     - caddy
  #   privileged: true

  gpt-bot:
    restart: unless-stopped
    container_name: gpt-bot
    image: ghcr.io/deanshub/gpt-bot:main
    env_file:
      - ./gpt-bot/.env
    volumes:
      - /media/external2/gpt-bot-data:/data
    privileged: true

  caddy:
    # image: caddy:stable
    build: ./caddy
    restart: unless-stopped
    container_name: caddy
    user: "1000:1000"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./caddy/site:/srv
      - /media/external/caddy_data/:/data/
      - /media/external/caddy_config/:/config/
      # - /media/external/auto-git/apps/:/apps/
    env_file:
      - ./caddy/.env
    networks:
      - caddy
    command:
      - caddy
      - run
      - "--config"
      - "/etc/caddy/Caddyfile"

  tailscale:
    restart: unless-stopped
    image: tailscale/tailscale
    privileged: true
    container_name: tailscale
    hostname: vpn.home.shubapp.com
    network_mode: host
    env_file: ./tailscale/.env
    environment:
      - TZ=Asia/Jerusalem
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun

  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: "1000:1000"
    networks:
      - caddy
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/mosquitto:/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - published: 1883
        target: 1883
    # env_file:
    #   - ./mosquitto/.env
    command: >
      sh -c '
        mkdir -p /mosquitto/log &&
        mkdir -p /mosquitto/data &&
        echo "${USER}:${PASSWORD}" > /mosquitto/passwordfile &&
        chmod 0700 /mosquitto/passwordfile &&
        mosquitto_passwd -U /mosquitto/passwordfile &&
        mosquitto -c /mosquitto/config/mosquitto.conf
      '

  filebrowser:
    restart: unless-stopped
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    networks:
      - caddy
    # ports:
    #   - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/filebrowser/settings:/config
      - /media/external/configs/filebrowser/db:/database
      - /media/external/library/downloads:/downloads
      - /media/external2/library/downloads:/downloads2
      - /media:/srv

  transmission:
    restart: unless-stopped
    container_name: transmission
    user: "1000:1000"
    image: linuxserver/transmission
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/library/downloads:/downloads
      - /media/external2/library/downloads:/downloads2
      - /media/external/configs/transmission:/config
      - /media/external/library/watch:/watch

  jackett:
    restart: unless-stopped
    networks:
      - caddy
    image: linuxserver/jackett:latest
    container_name: jackett
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/jackett:/config

  flaresolverr:
    restart: unless-stopped
    networks:
      - caddy
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"

  sonarr:
    restart: unless-stopped
    image: linuxserver/sonarr:latest
    container_name: sonarr
    user: "1000:1000"
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/sonarr:/config
      - /media/external/library/tv:/tv
      - /media/external/library/downloads:/downloads
      - /media/external2/library/downloads:/downloads2

  radarr:
    restart: unless-stopped
    image: linuxserver/radarr:latest
    container_name: radarr
    user: "1000:1000"
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/radarr:/config
      - /media/external/library/movies:/movies
      - /media/external/library/downloads:/downloads
      - /media/external2/library/downloads:/downloads2

  bazarr:
    restart: unless-stopped
    image: linuxserver/bazarr:latest
    container_name: bazarr
    user: "1000:1000"
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/bazarr:/config
      - /media/external/library/movies:/movies
      - /media/external/library/tv:/tv

  jellyfin:
    restart: unless-stopped
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - JELLYFIN_PublishedServerUrl=https://jellyfin.home.shubapp.com
    volumes:
      - /media/external/configs/jellyfin:/config
      - /media/external/cache/jellyfin:/cache
      - /media/external/library/tv:/data/tvshows
      - /media/external/library/movies:/data/movies
      - /media/external/videos:/data/videos
      - /media/external2:/data/external2
      - /media/external3:/data/external3
      - type: tmpfs
        target: /tmp-transcoding
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--cleanup"
