version: "3"
networks:
  caddy:
    external: true

services:
  homeassistant:
    restart: unless-stopped
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/homeassistant-config:/config
      # - ./home-assistant/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /media/external/library:/library
    privileged: true
    network_mode: host

  downloader:
    restart: unless-stopped
    container_name: downloader
    build: ./downloader
    # image:
    #environment:
    volumes:
      - /media/external:/media/external
    privileged: true

  caddy:
    # image: caddy:stable
    build: ./caddy
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      # - ./site:/srv
      - /media/external/caddy_data/:/data/
      - /media/external/caddy_config/:/config/
    env_file:
      - ./caddy/.env
    networks:
      - caddy
    command:
      - caddy
      - run
      - "--config"
      - "/etc/caddy/Caddyfile"

  tailscale:
    restart: unless-stopped
    image: tailscale/tailscale
    privileged: true
    container_name: tailscale
    hostname: vpn.home.shubapp.com
    network_mode: host
    env_file: ./tailscale/.env
    environment:
      - TZ=Asia/Jerusalem
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun

  filebrowser:
    restart: unless-stopped
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    networks:
      - caddy
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/filebrowser/settings:/config
      - /media/external/configs/filebrowser/db:/database
      - /media/external/library/downloads:/downloads
      - /media/external:/srv

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: '--cleanup'