services:
  friday:
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem
    container_name: friday
    user: "1000:1000"
    image: ghcr.io/deanshub/friday:main
    labels:
      url: "https://t.me/fridayJbot"
      color: "fuchsia"
      title: "Friday"
      category: "bot"
    env_file:
      - .env
    privileged: true
