networks:
  caddy:
    external: true

services:
  transmission:
    restart: unless-stopped
    container_name: transmission
    user: "1000:1000"
    image: linuxserver/transmission
    networks:
      - caddy
    labels:
      url: "https://torrent.{{ domain }}"
      title: "Torrent"
      category: "media"
    ports:
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/library/downloads:/downloads
      - /media/external/configs/transmission:/config
      - /media/external/library/watch:/watch
