networks:
  caddy:
    external: true

services:
  filebrowser:
    restart: unless-stopped
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    networks:
      - caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/filebrowser/settings:/config
      - /media/external/configs/filebrowser/db:/database
      - /media/external/library/downloads:/downloads
      - /media:/srv
