networks:
  caddy:
    external: true

services:
  home-project:
    container_name: home-project
    image: git.home.shubapp.com/deanshub/home-project:latest
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - DATA_DIR=/app/data
      - PORT=3004
    labels:
      url: "https://home-project.{{ domain }}"
      title: "Home Project"
      category: "tools & automation"
      color: "blue"
    volumes:
      - /media/external/library/home-project:/app/data
    ports:
      - "3004:3004"
