# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.31.153
    - 172.19.0.3
    - 0.0.0.0/0

smartir:

climate:
  - platform: smartir
    name: Attic AC
    unique_id: attic_ac
    device_code: 1340
    controller_data: remote.attic_remote_control
  - platform: smartir
    name: Livingroom AC
    unique_id: livingroom_ac
    device_code: 1560
    controller_data: remote.livingroom_remote_control
