services:
  - name: homeassistant
    label: HA
    url: https://ha.home.shubapp.com
    color: green
  - name: downloader
    label: Downloader
    url: https://t.me/ShubDownloadBot
    color: blue
  - name: friday
    label: Friday
    url: https://t.me/fridayJbot
    color: amber
  - name: shopping-bot
    label: Shopping Bot
    url: https://t.me/shopping_list_manager_bot
    color: rose
  - name: gpt-bot
    label: GPT Bot
    url: https://t.me/DecreeAiBot
    color: lime
  - name: caddy
    label: Caddy
  - name: tailscale
    label: Tailscale
  - name: mosquitto
    label: Mosquitto
  - name: filebrowser
    label: Files
    url: https://files.home.shubapp.com
    color: yellow
  - name: transmission
    label: Torrent
    url: https://torrent.home.shubapp.com
    color: red
  - name: prowlarr
    label: Prowlarr
    url: https://prowlarr.home.shubapp.com
    color: purple
  - name: flaresolverr
    label: Flaresolverr
    url: https://flaresolverr.home.shubapp.com
    color: pink
  - name: sonarr
    label: Sonarr
    url: https://sonarr.home.shubapp.com
    color: indigo
  - name: radarr
    label: Radarr
    url: https://radarr.home.shubapp.com
    color: teal
  - name: bazarr
    label: Bazarr
    url: https://bazarr.home.shubapp.com
    color: orange
  - name: jellyfin
    label: Jellyfin
    url: https://jellyfin.home.shubapp.com
    color: gray
  - name: watchtower
    label: Watchtower
  - name: n8n
    label: n8n
    url: https://n8n.home.shubapp.com
    color: violet
