services:
  tailscale:
    restart: unless-stopped
    image: tailscale/tailscale
    privileged: true
    container_name: tailscale
    hostname: vpn.home.shubapp.com
    network_mode: host
    env_file: .env
    environment:
      - TZ=Asia/Jerusalem
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - sys_module
    volumes:
      - /media/external/configs/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
