services:
  gpt-bot:
    restart: unless-stopped
    container_name: gpt-bot
    image: ghcr.io/deanshub/gpt-bot:main
    env_file:
      - .env
    volumes:
      - /media/external/gpt-bot-data:/data
    privileged: true
