networks:
  caddy:
    external: true

services:
  jackett:
    restart: unless-stopped
    networks:
      - caddy
    image: linuxserver/jackett:latest
    container_name: jackett
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/jackett:/config
