networks:
  caddy:
    external: true

services:
  caddy:
    build: .
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/etc/caddy/
      - ./site:/srv
      - ../../config.yaml:/srv/config.yaml
      - ../../ansible/bun-script/generate-caddyfile.ts:/srv/generate-caddyfile.ts
      - /media/external/caddy_data/:/data/
      - /media/external/caddy_config/:/config/
    env_file:
      - .env
    networks:
      - caddy
    command:
      - sh
      - -c
      - "yq -o=json /srv/config.yaml > /srv/config.json && cd /srv && bun run generate-caddyfile.ts && caddy run --config /etc/caddy/Caddyfile"
