networks:
  caddy:
    external: true

services:
  radarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - caddy
    ports:
      - 7878:7878
    labels:
      url: "https://radarr.{{ domain }}"
      color: "teal"
      title: "Radarr"
      category: "media"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /media/external/configs/radarr:/config
      - /media/external/library/movies:/movies
      - /media/external/library/downloads:/downloads
