- hosts: home_lab
  become: yes

  vars_prompt:
    - name: "static_ip"
      prompt: "Enter the static IP address you want for this host"
      default: "192.168.31.153"
      private: no
    - name: "username"
      prompt: "Enter your username for disk ownership"
      default: "{{ lookup('env', 'USER') }}"
      private: no

  vars:
    external_drives:
      - { src: "UUID=8265-B19B", path: "/media/drive1", fstype: "exfat" }
      - { src: "UUID=1C6CD5AE6CD582C6", path: "/media/drive2", fstype: "ntfs" }

  tasks:
    - name: Install mergerfs
      apt:
        name: mergerfs
        state: present

    - name: Install bun
      shell: curl -fsSL https://bun.sh/install | bash
      args:
        creates: /home/{{ username }}/.bun/bin/bun
      become_user: "{{ username }}"
      become: no

    - name: Create individual drive mount points
      file:
        path: "{{ item.path }}"
        state: directory
        mode: "0755"
      loop: "{{ external_drives }}"

    - name: Create merged mount point
      file:
        path: "/media/external"
        state: directory
        mode: "0755"

    - name: Mount individual drives
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "defaults,gid=docker,umask=002"
        state: mounted
      loop: "{{ external_drives }}"

    - name: Mount merged filesystem
      mount:
        path: "/media/external"
        src: "/media/drive1:/media/drive2"
        fstype: "fuse.mergerfs"
        opts: "defaults,allow_other,use_ino,cache.files=off,moveonenospc=true,category.create=mfs"
        state: mounted

  roles:
    - network
    - docker
    - minidlna
