- hosts: localhost
  become: yes

  tasks:
    - name: Handle configuration management
      include_tasks: tasks/config.yml

    - name: Handle storage configuration
      include_tasks: tasks/storage.yml

  roles:
    - network
    - docker
    - minidlna
