- hosts: home_lab
  become: yes

  vars_prompt:
    - name: "static_ip"
      prompt: "Enter the static IP address you want for this host (e.g. 192.168.31.153)"
      private: no

  roles:
    - network
    - docker
