- hosts: localhost
  become: yes

  tasks:
    - name: Install git-crypt
      apt:
        name: git-crypt
        state: present
        update_cache: yes

    - name: Handle configuration management
      include_tasks: tasks/config.yml

    - name: Handle storage configuration
      include_tasks: tasks/storage.yml

    - name: Configure network
      include_role:
        name: network

    - name: Install docker
      include_role:
        name: docker

    - name: Setup minidlna
      include_role:
        name: minidlna
