- hosts: home_lab
  become: yes

  vars_prompt:
    - name: "static_ip"
      prompt: "Enter the static IP address you want for this host"
      default: "192.168.31.153"
      private: no

  vars:
    external_drives:
      - { src: "UUID=49F680B8-A19F-4943-85A8-E62613BED1D8", path: "/media/external" }
      - { src: "UUID=0x00c01f25", path: "/media/external2" }

  tasks:
    - name: Create mount point directories
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ external_drives }}"

    - name: Mount external drives
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: xfs
        opts: defaults
        state: mounted
      loop: "{{ external_drives }}"

  roles:
    - network
    - docker
