networks:
  caddy:
    external: true

services:
  filebrowser:
    restart: unless-stopped
    image: gtstef/filebrowser:stable
    container_name: filebrowser
    networks:
      - caddy
    labels:
      url: "https://files.{{ domain }}"
      color: "red"
      title: "Files"
      category: "media"
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Jerusalem
      - FILEBROWSER_CONFIG=/config/config.yaml
      - FILEBROWSER_DATABASE_PATH=/data/database.sqlite
    volumes:
      - ./config.yaml:/config/config.yaml
      - /media/external/configs/filebrowser/db:/data
      - /media:/srv
